### ISSUE TITLE
Problem after MacOS installation

### ISSUE THREAD

**Issue by JeanDidier** [insilichem/tangram#9]
Hi there,

just after installing on MacOS, I ran tangram from the terminal and this message popped up:

     _____  _    _   _  ____ ____      _    __  __
    |_   _|/ \  | \ | |/ ___|  _ \    / \  |  \/  |
      | | / _ \ |  \| | |  _| |_) |  / _ \ | |\/| |
      | |/ ___ \| |\  | |_| |  _ <  / ___ \| |  | |
      |_/_/   \_\_| \_|\____|_| \_\/_/   \_\_|  |_|

 Tangram suite -- https://github.com/insilichem/tangram

 Launching UCSF Chimera via pychimera...

Traceback (most recent call last):
  File "/Users/jeandi/tangram/bin/pychimera", line 12, in <module>
    update_dict = pychimera.__main__.run()
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/pychimera/__main__.py", line 6, in run
    pychimera.main()
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/pychimera/core.py", line 341, in main
    patch_environ(nogui=args.nogui)
  File "/Users/jeandi/tangram/lib/python2.7/site-packages/pychimera/core.py", line 164, in patch_environ
    os.execve(sys.executable, [sys.executable] + sys.argv, os.environ)
OSError: [Errno 2] No such file or directory

**Comment by jaimergp** [comment]
Really interesting, `sys.executable` should always exist. Since this is running on a Mac (which version?), and I recall that we override that path in Mac only, maybe I should add some checks in there.

It would be nice if you could also print the output of the following command:

 `env | sort`

How did you install it? With the `*.sh` installer (probably, given the path) or via the conda metapackage? If it's the first case, which version?

**Comment by jaimergp** [comment]
Yep, I checked the code and you could probably workaround the bug while I fix it if the right `CHIMERADIR` value is set.

This environment variable should point to the Chimera installation path. In a Mac, this is something like `/Applications/Chimera.app/Contents/Resources`. This directory should contain directories like `bin`, `lib`, `share` and so on.

**Comment by JeanDidier** [comment]
Great, exporting the CHIMERADIR to this Resources path makes the trick and Pychimera starts...but no trace of the tangram submenu.

**Comment by jaimergp** [comment]
Since `CHIMERADIR` was needed, I'd say that the installer was not able to automatically add the new package origin to the list of directories Chimera scans at launch to load the extensions. The workaround is simply doing it yourself (the installer should have printed something along these lines, IIRC).

Quoting [our documentation](https://tangram-suite.readthedocs.io/en/latest/install.html#install-only-one-specific-extension):

> Once completed, tell UCSF Chimera to look for new extensions in the chosen environment. To do that, open UCSF Chimera and go to Favorites> Add to Favorites/Toolbar. In the newly opened dialog, specify the env location in the bottom box. In this case, the extensions location will be something like `$CONDA_PREFIX/lib/python2.7/site-packages`.

In this case, your path is `/Users/jeandi/tangram/lib/python2.7/site-packages/`.
